RTA-Project-MVC/Controllers/NewsController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using PagedList;
using RTA_Project_BL.Models;
using RTA_Project_BL.Services;
using RTA_Project_DAL.enums;
using RTA_Project_MVC.Models;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;

namespace RTA_Project_MVC.Controllers
{
    public class NewsController : Controller
    {

        private readonly IArticleService _articleService;

        private readonly IMapper _mapper;

        public NewsController(IArticleService articleService, IMapper mapper)
        {
            _articleService = articleService;

            _mapper = mapper;
        }

        // GET: News
        public ActionResult Index(int? page)
        {

            int pageSize = 6;
            int pageNumber = (page ?? 1);

            var articlesBL = _articleService.QueryArticles((int)Lang.Rus);
            var articlesPageBL = articlesBL.ToPagedList(pageNumber, pageSize);

            var mappedList = _mapper.Map<IEnumerable<ArticleViewModel>>(articlesPageBL);

            var pagedResult = new StaticPagedList<ArticleViewModel>(mappedList, articlesPageBL.GetMetaData());

            return View(pagedResult);
        }

        // GET: News/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: News/Create
        [Authorize(Roles = "Host")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        [HttpPost]
        [Authorize(Roles = "Host")]
        public ActionResult Create(ArticleViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.LangId = Lang.Rus;

            var articleBL = _mapper.Map<ArticleBL>(model);

            articleBL.AuthorId = User.Identity.GetUserId();
            articleBL.Date = DateTime.Now;

            _articleService.Create(articleBL);

            return RedirectToAction("Index");
        }

        // GET: News/Edit/5
        public ActionResult Edit(int id)
        {
            var articleBL = _articleService.GetById(id);

            var model = _mapper.Map<ArticleViewModel>(articleBL);

            model.Content = WebUtility.HtmlDecode(model.Content);

            return View(model);
        }

        // POST: News/Edit/5
        [HttpPost]
        public ActionResult Edit(ArticleViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var articleBL = _mapper.Map<ArticleBL>(model);

            _articleService.Update(articleBL);

            return RedirectToAction("Index");
        }


        // POST: News/Delete/5
        [HttpDelete]
        [Authorize(Roles = "Host")]
        public ActionResult Delete(int id)
        {
            _articleService.Delete(id);

            return new EmptyResult();
        }
    }
}

RTA-Project-MVC/Controllers/ProfileController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using RTA_Project_BL.Models;
using RTA_Project_BL.Services;
using RTA_Project_MVC.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace RTA_Project_MVC.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {

        private readonly IPlayerService _playerService;

        private readonly IMapper _mapper;

        public ProfileController(IPlayerService playerService, IMapper mapper)
        {
            _playerService = playerService;

            _mapper = mapper;
        }

        // GET: Profile/?name=
        [AllowAnonymous]
        public ActionResult Index(string name)
        {
            PlayerBL playerBL;
            if (name == null)
            {
                if (User.Identity.IsAuthenticated)
                {
                    var userId = User.Identity.GetUserId();
                    playerBL = _playerService.GetByAccountId(userId);
                }
                else
                {
                    return RedirectToAction("LogIn", "Account");
                }
            }
            else
            {
                playerBL = _playerService.GetByName(name);
            }

            if (playerBL != null)
            {


                var model = _mapper.Map<PlayerProfileViewModel>(playerBL);
                               

                return View(model);
            }

            return RedirectToAction("Register");
        }


        // GET: Profile/Register
        public ActionResult Register()
        {
            return View();
        }

        // POST: Profile/Create
        [HttpPost]
        public ActionResult Create(PlayerProfileCreateModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                if (!_playerService.QueryAll().Any(p=>p.AccountId==userId))
                {
                    var key = Guid.NewGuid().ToString();
                    var player = new PlayerBL
                    {
                        Name = model.Nickname,
                        AccountId = userId,
                        GuidKey = key,

                        Stats = new PlayerStatsBL
                        {
                            RatingClass = "B",
                            RatingPointsCurrent = 1200,
                            RatingPointsMax = 1200
                        }
                    };

                    _playerService.Create(player);
                }
            }

            return RedirectToAction("Index");

        }

        // POST: Profile/Link
        [HttpPost]
        public ActionResult Link(PlayerProfileLinkModel model)
        {
            if (ModelState.IsValid)
            {
                var accountId = User.Identity.GetUserId();
                _playerService.LinkAccountToPlayer(accountId, model.GuidKey);
            }

            return RedirectToAction("Index");
        }



        public JsonResult CheckNameIsTaken(string Nickname)
        {
            return Json(!_playerService.CheckIfNameExists(Nickname), JsonRequestBehavior.AllowGet);
        }

        public JsonResult CheckKeyIsInvalid(string GuidKey)
        {
            return Json(_playerService.CheckIfKeyExists(GuidKey), JsonRequestBehavior.AllowGet);
        }

    }
}

RTA-Project-MVC/Controllers/StatisticsController.cs
using RTA_Project_BL.Models;
using RTA_Project_BL.Services;
using RTA_Project_MVC.Helpers;
using RTA_Project_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web.Mvc;

namespace RTA_Project_MVC.Controllers
{
    public class StatisticsController : Controller
    {

        private readonly ITournamentService _tournamentService;
        private readonly IHeroService _heroService;

        private readonly IStatsHelper _statsHelper;

        public StatisticsController(ITournamentService tournamentService, IHeroService heroService, IStatsHelper statsHelper)
        {
            _tournamentService = tournamentService;
            _heroService = heroService;

            _statsHelper = statsHelper;
        }

        // GET: Statistics
        public ActionResult Index()
        {

            return View(new StatisticsFilterModel());
        }


        public ActionResult GetStatistics(StatisticsFilterModel model)
        {
            var filtersForGames = new List<Expression<Func<GameBL, bool>>>();
            if (model.FilterByDate)
            {
                Expression<Func<GameBL, bool>> dateFilter = g => g.DateSubmitted >= model.DateFrom && g.DateSubmitted <= model.DateTo;
                filtersForGames.Add(dateFilter);
            }

            if (!model.GetForSingleFaction)
            {
                var games = _tournamentService.GetTournamentGames(null, filtersForGames.ToArray());

                if (model.FilterByDate)
                    games = games.Where(g => g.DateSubmitted >= model.DateFrom && g.DateSubmitted <= model.DateTo);

                var statsModel = _statsHelper.RecoverAllFactionsStats(games.ToList());

                return PartialView("_AllFactionsStatsPartial", statsModel);
            }
            else
            {
                var factionId = model.FactionId;

                var heroes = _heroService.GetAllByFaction(model.FactionId);
                var heroesId = heroes.Select(h => h.Id).ToArray();

                Expression<Func<GameBL, bool>> factionFilter = g => g.Faction1Id == factionId || g.Faction2Id == factionId;
                filtersForGames.Add(factionFilter);

                var games = _tournamentService.GetTournamentGames(null, filtersForGames.ToArray());


                var statsModel = _statsHelper.RecoverFactionHeroesStats(games.ToList(), factionId, heroesId);
                var heroNames = heroes.Select(h => h.NameRus);
                statsModel.HeroNames = heroNames.ToArray();

                return PartialView("_FactionHeroesStatsPartial", statsModel);
            }

        }



    }
}

RTA-Project-MVC/Controllers/TournamentController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using RTA_Project_BL.Models;
using RTA_Project_BL.Services;
using RTA_Project_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RTA_Project_MVC.Controllers
{
    public class TournamentController : Controller
    {

        private readonly ITournamentService _tournamentService;
        private readonly IPlayerService _playerService;

        private readonly IMapper _mapper;

        public TournamentController(ITournamentService tournamentService, IPlayerService playerService, IMapper mapper)
        {
            _tournamentService = tournamentService;
            _playerService = playerService;
            _mapper = mapper;
        }


        // GET: Tournament
        public ActionResult Index(int? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            var tournamentsBL = _tournamentService.QueryAll().OrderByDescending(t => t.DateCreated);
            var tournamentsPageBL = tournamentsBL.ToPagedList(pageNumber, pageSize);

            var mappedList = _mapper.Map<IEnumerable<TournamentPreviewModel>>(tournamentsPageBL);

            var pagedResult = new StaticPagedList<TournamentPreviewModel>(mappedList, tournamentsPageBL.GetMetaData());

            return View(pagedResult);
        }

        // GET: Tournament/Details/5
        public ActionResult Details(int id)
        {
            var tournamentBL = _tournamentService.GetById(id);

            var tournament = _mapper.Map<TournamentDetailsModel>(tournamentBL);

            var hosts = new List<string>();
            if (tournamentBL.HostsId != null)
            {
                var hostsId = tournamentBL.HostsId.Split(';');

                var userManager = Request.GetOwinContext().GetUserManager<ApplicationUserManager>();               
                foreach (var hostId in hostsId)
                {
                    var host = userManager.Users.FirstOrDefault(u => u.Id == hostId);
                    if (host != null)
                        hosts.Add(host.UserName);
                }               
            }
            tournament.TournamentHosts = hosts;

            return View(tournament);
        }

        // GET: Tournament/Create
        [Authorize(Roles = "Host")]
        public ActionResult Create()
        {

            var userManager = Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var roleManager = Request.GetOwinContext().Get<ApplicationRoleManager>();

            var role = roleManager.Roles.Single(r => r.Name == "Host");
            var hosts = userManager.Users.Where(u => u.Roles.Any(r => r.RoleId == role.Id)).Select(x => new SelectListItem
            {
                Text = x.UserName,
                Value = x.Id
            }).ToList();

            var userId = User.Identity.GetUserId();
            hosts.Remove(hosts.First(x => x.Value == userId));

            var model = new TournamentCreateModel() { Year = DateTime.Now.Year, HostsAvailable = hosts };
            return View(model);
        }

        // POST: Tournament/Create
        [HttpPost]
        [Authorize(Roles = "Host")]
        public ActionResult Create(TournamentCreateModel model, params string[] selectedHost)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var modelBL = _mapper.Map<TournamentBL>(model);

            if (selectedHost == null)
                selectedHost = new string[] { };

            var userId = User.Identity.GetUserId();
            modelBL.HostsId = $"{userId};{string.Join(";", selectedHost)}";
            modelBL.DateCreated = DateTime.Now;

            _tournamentService.Create(modelBL);

            return RedirectToAction("Index");
        }

        // GET: Tournament/Edit/5
        [Authorize(Roles = "Host")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Tournament/Edit/5
        [HttpPost]
        [Authorize(Roles = "Host")]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: Tournament/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        // POST: Tournament/Register/5
        [HttpPost]
        public ActionResult Register(int id)
        {

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("LogIn", "Account");
            }

            var userId = User.Identity.GetUserId();
            var player = _playerService.GetByAccountId(userId);

            if (player == null)
            {
                return RedirectToAction("Register", "Profile");
            }

            _tournamentService.RegisterPlayer(id, player.Id);

            return RedirectToAction("Index");
        }

    }
}

RTA-Project-MVC/Views/Shared/_AccountJogPartial.cshtml
@using Microsoft.AspNet.Identity


@{
    int day = (int)DateTime.Now.DayOfWeek;
    string imgDoorNormal = $"/Resources/ui/jog/DoorNormal_{day}.png";
    string imgDoorPushed = $"/Resources/ui/jog/DoorPushed_{day}.png";
}


<style>
    .jog-btn.center {
        background: url('@imgDoorNormal')
    }

    .jog-btn.center:active {
        background: url('@imgDoorPushed')
    }
</style>




@if (Request.IsAuthenticated)
{
    using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
    {
        @Html.AntiForgeryToken()

        <label id="greetings-panel">@User.Identity.GetUserName()</label>     

        <div class="jog-5">

            <a class="jog-btn upper left" href="@Url.Action("Index","Profile")">
                <span class="tooltiptext">Мой профиль</span>
            </a>
            @if (User.IsInRole("Admin"))
            {
            <a class="jog-btn upper right adm-btn" href="@Url.Action("Index","UsersAdmin")">
                <span class="tooltiptext">Админ</span>
            </a>
            }
            else
            {
                <a class="jog-btn upper right reg-btn" id="grayed-out"></a>
            }

                <a class="jog-btn center" href="javascript:document.getElementById('logoutForm').submit()">
                    <span class="tooltiptext">Выход</span>
                </a>

                <a class="jog-btn lower left" href="#">
                    <span class="tooltiptext">Мои матчи</span>
                </a>
                <a class="jog-btn lower right" href="@Url.Action("Index","Manage")">
                    <span class="tooltiptext">Настройки аккаунта</span>
                </a>

        </div>

    }
}

else
{
    <label id="greetings-panel">Гость</label>

    <div class="jog-5">

        <a class="jog-btn upper left" id="grayed-out"></a>
        <a class="jog-btn upper right reg-btn" href="@Url.Action("Register","Account")">
            <span class="tooltiptext">Регистрация</span>
        </a>
        <a class="jog-btn center" href="@Url.Action("LogIn","Account")">
            <span class="tooltiptext">Вход</span>
        </a>
        <a class="jog-btn lower left" id="grayed-out"></a>
        <a class="jog-btn lower right" id="grayed-out"></a>

    </div>

}

RTA-Project-MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div id="maincontainer">


        <div id="left">

            <div id="ltop"></div>

            <div id="jog-area">


                @Html.Partial("_AccountJogPartial")


            </div>

            <div id="lseparator"></div>

            <div id="nav-block">
                <a class="btn btn-block" href="http://forum.heroesleague.ru/viewtopic.php?f=27&t=20883">
                    <img src="/Resources/icons/H5Pathfinding.png" height="34" width="34" />
                    Все об RTA
                </a>
                <a class="btn btn-block" href="@Url.Action("Index", "News")">
                    <img src="/Resources/icons/H5BasicLeadership.png" height="34" width="34" />
                    Новости
                </a>
                <a class="btn btn-block" href="@Url.Action("Index", "Tournament")">
                    <img src="/Resources/icons/H5Empathy.png" height="34" width="34" />
                    Турниры
                </a>
                <a class="btn btn-block" href="http://forum.heroesleague.ru/viewtopic.php?f=14&t=22488">
                    <img src="/Resources/icons/ExpPic.png" height="34" width="34" />
                    Рейтинг
                </a>
                <a class="btn btn-block" href="@Url.Action("Index", "Statistics")">
                    <img src="/Resources/icons/H5Scholar.png" height="34" width="34" />
                    Статистика
                </a>
                <a class="btn btn-block" href="#">
                    <img src="/Resources/icons/H5ExpertTrainer.png" height="34" width="34" />
                    Руководства
                </a>
                <a class="btn btn-block" href="http://forum.heroesleague.ru/">
                    <img src="/Resources/icons/H5Diplomacy.png" height="34" width="34" />
                    Форум
                </a>
                <a class="btn btn-block" href="https://discord.gg/DCxUAvY">
                    <img src="/Resources/icons/discord-logo.png" height="34" width="34" />
                    Сервер Discord
                </a>
            </div>

            <div id="lseparator"></div>

            @*<div id="larea"></div>
            <div id="lseparator"></div>*@

            <div id="lbot"></div>

        </div>

        <div id="right">


            <div id="rtop"></div>

            <div id="rtop2"></div>
            <div id="ltcorn"></div>
            <div id="rtcorn"></div>


            <div class="body-content">

                @RenderBody()

            </div>

            <div id="rbot2"></div>
            <div id="ltcorn2"></div>
            <div id="rtcorn2"></div>


        </div>



        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>

</body>
</html>